export enum CREDENTIAL {
    BROWSER_NOTIFY_UI_USERID = "BROWSER_NOTIFY_UI_USERID",
    BROWSER_NOTIFY_UI_COMPANY = "BROWSER_NOTIFY_UI_COMPANY",
    BROWSER_NOTIFY_UI_SUBSCRIBED = "BROWSER_NOTIFY_UI_SUBSCRIBED"
}

export enum QUERY_STATUS {
    UNINITIALIZED = 0,
    LOADING = 1,
    SUCCESS = 2,
    ERROR = 3,
}